- name: Configuring backend server
  hosts: backend
  become: yes
  vars:

  tasks:
   - name: disable nodejs module
     ansible.builtin.command: "dnf module disable nodejs -y"

   - name: enable nodejs 20 module
     ansible.builtin.command: "dnf module enable nodejs:20 -y"

   - name: install nodejs
     ansible.builtin.dnf:
        name: nodejs
        state: present

   - name: cerate user for backend app
     ansible.builtin.user:
       name: expense
       
     