- name: configure database server
  hosts: db
  become: yes
  vars:
    login_host: db.chandradevops.online
  tasks:

    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: check db connection
      community.mysql.mysql_info:
        login_host: "{{ login_host }}"
        login_user: root
        login_password: ExpenseApp@1
        filter: version
      register: mysql_connection_info
      ignore_errors: yes

    - name: installing python mysql dependencies
      ansible.builtin.pip:
        name: 
        - PyMySQL
        - cryptography
      executable: pip3.9
      when: mysql_connection_info is failed
