- name: configure database server
  hosts: db
  become: yes
  vars:
    login_host: db.chandradevops.online
  tasks:

    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: check db connection
      community.mysql.mysql_info:
        login_host: "{{ login_host }}"
        login_user: root
        login_password: ExpenseApp@1
        register: mysql_connection_info
        filter: version
        ignore_errors: yes